### ISSUE TITLE
parsing errors for the complex triplet model and the transpose operation in general

### ISSUE THREAD

**Issue by Yong-Du** [LSartore/pyrate#7]
Hi,

I am following strictly the manual for introducing the complex triplet model, but I encounter the following parsing error while generating the beta functions. Any suggestions?

---
Loading the YAML file: /Users/yongdu/Documents/EFT-loop/code/pyrate-2.0.0/pyrate3.0/models/CTHM.model ... Done.

Loading the model ... 

Error while parsing the term 'Delta[i,j] : tFund[a,i,j]delta[a]'.

---

By the way, I also have a question regarding transposing. This is because in the most general case of the potential of the complex triplet model, there is one term goes like $H^T\epsilon\Delta^\dagger H$, where H is the SM Higgs doublet and $\Delta$ is the complex triplet. It seems to me that the transpose operation is currently missing in the definition of pyrate. If true, is there any way to include this term in pyrate? 

Thanks and best,
Yong

**Comment by LSartore** [comment]
Hi,
Could you please share the 'Definitions' section of your model file ? This will probably help in identifying the issue.

Regarding your question, any kind of transposition is in principle possible since the indices appear explicitly in the definition of the operators. For objects that can be seen as rank-1 tensors (e.g. the Higgs field), H and H^T are strictly equivalent in the explicit index notation.
To implement the operator that you mentioned above (or any other one), the recipe is to first convert the matrix-form expression in an index notation:
 
H^T \epsilon \Delta^\dagger H  ->  H[i] Eps[i,j] DeltaDag[j,k] H[k] ,

assuming that DeltaDag has been defined earlier in the model file.

I hope this will help. Let me know if this does not work as expected, or if you have any other question.

Cheers,
Lohan

**Comment by Yong-Du** [comment]
Hi Lohan,

My `Definitions` section is attached below, and let me mention that it is the only part I change in the original `SM.model` file. I hope this can help identify the issues.

Regarding the transposition, what you suggested was exactly what I thought and had tried before raising this issue, but unfortunately it failed, complaining that `}` is expected instead of `[` from the `H[i]` part. I think this is probably somehow related to the parsing issue. So I will try that again when we fix the parsing error.

Thanks and best,
Yong

---
    Definitions: {
        tFund : t(SU2, 2),
        Delta[i,j] : tFund[a,i,j] delta[a],
        DeltaDag[i,j] : tFund[a,i,j] deltabar[a],
        Tr2 : DeltaDag[i,j] Delta[j,i],
        Tr4 : DeltaDag[i,j] Delta[j,k] DeltaDag[k,l] Delta[l,i],
        Htilde[i] : Eps[i,j]*Hbar[j]
    },

**Comment by LSartore** [comment]
Hi,
Thanks for your reply. 

First, let me acknowledge that PyR@TE's parser could very much be improved in the way error are raised. From your last message, it seems that you have simply forgotten to define the new scalar triplet 'delta', within the ComplexScalars section. For instance:

ComplexScalars: {
    H: {RealFields: [Pi, Sigma], Norm: 1/sqrt(2), Qnb : {U1: 1/2, SU2L: 2, SU3c: 1}},
    delta : {RealFields: [detlaR, deltaI], Norm: 1/sqrt(2), Qnb: {U1: 1, SU2L : 3, SU3c: 1}}
}

In principle this should solve all the issues. In particular, I suspect that the other errors that you may get are related to the fact that Delta is ill-defined.

Hope this helps.
Lohan

**Comment by Yong-Du** [comment]
Hi Lohan,

Thank you for the prompt reply. It worked indeed after defining the `delta` filed as you suggested -- I previously misunderstood that once one had specified the fundamental gauge group, the scalar fields in its adjoint representation would be identified automatically.

In the meantime, the issue associated with the transpose operation I mentioned earlier now also goes away.

Thanks again and best,
Yong
